# Generated by Django 3.0.4 on 2020-03-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='', max_length=15, verbose_name='Номер Телефона')),
                ('document', models.CharField(default='Паспорт', max_length=30, verbose_name='Вид документа')),
                ('document_serises', models.CharField(default='', max_length=15, verbose_name='Серия документа')),
                ('document_number', models.CharField(default='', max_length=15, verbose_name='Номер документа')),
                ('first_name', models.CharField(default='', max_length=20, verbose_name='Имя:')),
                ('last_name', models.CharField(default='', max_length=20, verbose_name='Фамилия:')),
                ('middle_name', models.CharField(default='', max_length=20, verbose_name='Отчество')),
                ('ready', models.BooleanField(default=False, verbose_name='Согласен(-на) на рассылку сообщений')),
            ],
        ),
    ]
