# Generated by Django 3.0.4 on 2020-03-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='document',
            field=models.CharField(choices=[('Паспорт', 'Паспорт'), ('Водительское удостоверение', 'Водительское удостоверение')], default='Паспорт', max_length=30, verbose_name='Вид документа'),
        ),
    ]
