# Generated by Django 2.2.6 on 2020-03-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20200312_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='start_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время регистрации'),
        ),
    ]
