# Generated by Django 3.0.4 on 2020-03-16 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='document_serises',
            new_name='document_series',
        ),
    ]
