# Generated by Django 3.0.4 on 2020-03-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20200316_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bonus',
            field=models.IntegerField(default=0, max_length=4, verbose_name='Бонусный счет:'),
        ),
    ]
