# Generated by Django 2.2.7 on 2020-05-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bonus',
            field=models.IntegerField(default=0, verbose_name='Бонусный счет:'),
        ),
    ]
