# Generated by Django 3.1.7 on 2021-06-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_client_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.CharField(default='-', max_length=255, verbose_name='Комментарий:'),
        ),
    ]
