# Generated by Django 3.0.4 on 2020-03-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='start_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время начала поездки'),
        ),
    ]
