# Generated by Django 3.0.4 on 2020-03-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_ride_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='tech',
            field=models.CharField(choices=[('Самокат', 'Самокат'), ('Байк', 'Байк'), ('Велосипед', 'Велосипед')], default='', max_length=20, verbose_name='Техника:'),
        ),
        migrations.AddField(
            model_name='ride',
            name='tech_number',
            field=models.CharField(default='', max_length=2, verbose_name='Номер техники'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='tariff',
            field=models.CharField(choices=[('Полчаса', 'Полчаса'), ('Час', 'Час'), ('Поминутный', 'Поминутный')], default='', max_length=20, verbose_name='Тариф:'),
        ),
    ]
