# Generated by Django 3.0.4 on 2020-03-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0004_auto_20200312_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='tech_quantity',
            field=models.CharField(default='', max_length=20, verbose_name='Количество Техники:'),
        ),
    ]
