# Generated by Django 2.2.6 on 2020-03-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0005_auto_20200312_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='summ',
        ),
        migrations.AddField(
            model_name='ride',
            name='cena',
            field=models.IntegerField(default=1, verbose_name='Цена'),
        ),
    ]
