# Generated by Django 2.2.6 on 2020-03-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0006_auto_20200314_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='payment_type',
            field=models.CharField(choices=[('Искра', 'Искра'), ('Набережная', 'Набережная')], default='', max_length=20, verbose_name='Точка выдачи:'),
        ),
        migrations.AddField(
            model_name='ride',
            name='place_from',
            field=models.CharField(choices=[('Искра', 'Искра'), ('Набережная', 'Набережная')], default='', max_length=20, verbose_name='Точка выдачи:'),
        ),
        migrations.AddField(
            model_name='ride',
            name='place_to',
            field=models.CharField(choices=[('Искра', 'Искра'), ('Набережная', 'Набережная')], default='', max_length=20, verbose_name='Точка сдачи:'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время начала поездки'),
        ),
    ]
