# Generated by Django 2.2.6 on 2020-03-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0008_auto_20200315_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='payment_type',
            field=models.CharField(choices=[('Наличный', 'Наличный'), ('Безналичный', 'Безналичный')], default='', max_length=20, verbose_name='Метод оплаты:'),
        ),
    ]
