# Generated by Django 3.0.4 on 2020-03-16 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0009_auto_20200315_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 17, 9, 47, 489556), verbose_name='Время начала поездки'),
        ),
    ]
