# Generated by Django 3.0.4 on 2020-03-19 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0010_ride_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 17, 6, 12, 425218), verbose_name='Время окончания поездки'),
        ),
    ]
