# Generated by Django 3.0.4 on 2020-03-19 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0012_auto_20200319_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 17, 18, 53, 97840), verbose_name='Время окончания поездки'),
        ),
    ]
