# Generated by Django 3.0.4 on 2020-03-19 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0014_auto_20200319_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 17, 20, 24, 377081), verbose_name='Время окончания поездки'),
        ),
    ]
