# Generated by Django 3.0.4 on 2020-03-22 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0017_auto_20200319_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 16, 11, 14, 349943), verbose_name='Время окончания поездки'),
        ),
    ]
