# Generated by Django 2.2.7 on 2020-06-05 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0021_auto_20200605_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 22, 13, 3, 379690), verbose_name='Время окончания поездки'),
        ),
    ]
