# Generated by Django 2.2.7 on 2020-06-05 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0022_auto_20200605_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 22, 14, 57, 331226), verbose_name='Время окончания поездки'),
        ),
    ]
