# Generated by Django 3.1.7 on 2021-06-12 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0026_auto_20200728_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 21, 57, 6, 30365), verbose_name='Время окончания поездки'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='payment_type',
            field=models.CharField(choices=[('Наличный', 'Наличный'), ('Безналичный', 'Безналичный'), ('Смешанный', 'Смешанный')], default='', max_length=20, verbose_name='Метод оплаты:'),
        ),
    ]
