# Generated by Django 3.1.7 on 2021-06-12 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0027_auto_20210612_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 21, 59, 1, 490253), verbose_name='Время окончания поездки'),
        ),
    ]
