# Generated by Django 3.0.4 on 2020-03-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(choices=[('Самокат', 'Самокат'), ('Байк', 'Байк'), ('Велосипед', 'Велосипед')], default='', max_length=20, verbose_name='Техника:')),
                ('tech_number', models.CharField(default='', max_length=20, verbose_name='Номер техники:')),
                ('reason', models.TextField(default='', max_length=150, verbose_name='Вид поломки')),
            ],
        ),
    ]
