# Generated by Django 2.2.6 on 2020-03-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='start_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время поломки'),
        ),
    ]
